config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
   
  end
  resources :sessions, only: [:create,:destroy]
  resources :posts , only: [:create,:destroy, :edit,:update,:show]
  resources :relationships , only: [:create,:destroy]

  root :to => 'blogs#home'
  get '/about' => 'blogs#about'
  get '/contact' =>'blogs#contact'
  
  get '/signup' => 'users#new'
  post '/send_email' => 'blogs#send_email'
  
  delete '/signout' => 'sessions#destroy' 
 
 

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

def home
  if signed_in?
    @post=current_user.posts.build 
    @feed_items=current_user.feed.paginate(page: params[:page])
  end
end
def about
end

def contact
end 

def send_email
  # should send email and redirect to home page.
 redirect_to root_path, :notice => "Email sent with subject #{params['subject']} and body #{params['body']}"

end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/about.html.erb
<% provide(:title, "About Us")%>
<div class="jumbotron">
 <div class="container">
 <h1>About Us</h1>
 <p>This is the about page!</p>
 </div>
</div>

app/views/blogs/contact.html.erb
<%= provide(:title, "Contact Us")%>

<div class="jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-sm-5">
                <h1>Contact Us</h1>
                <p>This is the contact us page!</p>
          </div>
          <div class="col-sm-7">
           <%= form_tag(send_email_path , :class => 'form-horizontal')  do %>
              <div class="form-group">
                <%= label_tag 'subject' ,"Subject", :class => 'col-sm-2 control-label' %>
                 <div class="col-sm-10">
                  <%= text_field_tag 'subject',"", :class =>"form-control" %>
                </div>
              </div>
              
              <div class="form-group">
                <%= label_tag 'body','Body' , :class => 'col-sm-2 control-label' %>
                 <div class="col-sm-10">
                  <%= text_area_tag 'body',"", :class =>"form-control" %>
                </div>
              </div>
              
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= submit_tag 'Send', :class => 'btn btn-primary' %>
                </div>
              </div>
            <% end %>
            
          </div>
        </div>
      </div>
</div>


app/views/blogs/home.html.erb
<% if signed_in?%>
	<div calss="row">
		<div class="col-md-4">
		<aside class="span4">
			<section>
				<%= render 'shared/user_info'%>
			</section>
			<section>
				<%= render 'shared/stats'%>
			</section>
			<section>
				<%= render 'shared/post_form'%>				
			</section>
		</aside>
		</div>
		<div class="span8">
			<div class="col-md-8">
			<h3>Post Feed</h3>
			<%= render'shared/feed'%>
			</div>
		</div>
	</div>
	
<%else%>
	<!-- Main jumbotron for a primary marketing message or call to action -->!        
  	<div class="jumbotron">
    	<div class="container">      
 	 	<h1>Home</h1>        
 	 	<p>This is our blog's homepage.</p>    
 	 	<p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>      
 		</div>   
   	</div>   
   	<div class="container">      
 		<!-- Example row of columns -->      
 		<div class="row">      
 			<div class="col-md-4">         
 				<h2>Heading</h2>         
 				<p>Some information here..</p>         
 				<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>       
 			</div>     
 			<div class="col-md-4">         
 				<h2>Heading</h2>         
 				<p>Some information here..</p>         
 				<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>      
 			</div>   
 			<div class="col-md-4">       
 				<h2>Heading</h2>         
 				<p>Some information here..</p>       
 				<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>      
 			</div>
 		</div>     
 		<hr>
 		<footer>
 			<p>&copy; Company 2014</p>    
 		</footer>
 		</div> <!-- /container -->

	


<%end%>