config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
   
  end
  resources :sessions, only: [:create,:destroy]
  resources :posts , only: [:create,:destroy, :edit,:update,:show]
  resources :relationships , only: [:create,:destroy]

  root :to => 'blogs#home'
  get '/about' => 'blogs#about'
  get '/contact' =>'blogs#contact'
  
  get '/signup' => 'users#new'
  post '/send_email' => 'blogs#send_email'
  
  delete '/signout' => 'sessions#destroy' 
 
 

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <b><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.to_s.downcase %> from being saved:</b>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<%if @feed_items.any?%>
	<ol class="posts">
		<%= render partial:'shared/feed_item',collection:@feed_items%>
	</ol>
	<%= will_paginate @feed_items%>
		
<%end%>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id%>">
	<div class="row">
		<div class="col-md-4">
			<%= link_to gravatar_for(feed_item.user),feed_item.user%>
			<span class="user">
				<%=link_to feed_item.user.name,feed_item.user%>
			</span>
		</div>
		<div class="col-md-8">
			<div class ="row">
				<div class="col-md-3">
					<h3><span class="title"><%= feed_item.title%></span></h3>
				</div>
			</div>
		<div class ="row">
			<div class="col-md-8">
				<span class="content"><%= truncate(feed_item.content,:length=>50)%></span>
			</div>
		</div>
		<div class="row">
			<div class="col-md-5">
				<span class="timestamp">
					Posted <%= time_ago_in_words(feed_item.created_at)%> ago.
				</span>
			</div>
		<div class="col-md-3">
		<% if current_user?(feed_item.user)%>
			<%= link_to "delete",feed_item,method: :delete, data: {confirm: "You sure?"}  %>
			<%= link_to "edit",edit_post_path(feed_item) %>
			<%= link_to "details",post_path(feed_item)%>
		<% end%>
		</div>
	</div>
</div>
</li>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f|%>
	<%= render 'shared/error_messages', object: @post%>
	<div class="field">
		
		<div class="row">
			<div class="col-md-6">
				<span class="title"><%=f.text_area :title ,placeholder: "Title" ,:size=>"30x1"%></span>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<span class="title"><%=f.text_area :content, placeholder: "Compose new post....",:cols =>"30",:rows =>"10"%></span>
			</div>
		</div>
		
		
		
	</div>
	<%= f.submit "Post", class:"btn btn-large btn-primary"%>
<%end%>

app/views/shared/_stats.html.erb
<% @user ||= current_user%>

<div class="stats">
	<a href="<%= following_user_path(@user)%>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count%>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user)%>">
		<strong id="followers" class="stat">
			<%= @user.followers.count%>
		</strong>
		followers
	</a>
</div>
		

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user)%>">
	<%= gravatar_for current_user,size:52%>
</a>
<h1><%= current_user.name%></h1>
<span><%= link_to"view my profile",current_user%>
</span>
<span><%= pluralize(current_user.posts.count,"post")%>
</span>