config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
   
  end
  resources :sessions, only: [:create,:destroy]
  resources :posts , only: [:create,:destroy, :edit,:update,:show]
  resources :relationships , only: [:create,:destroy]

  root :to => 'blogs#home'
  get '/about' => 'blogs#about'
  get '/contact' =>'blogs#contact'
  
  get '/signup' => 'users#new'
  post '/send_email' => 'blogs#send_email'
  
  delete '/signout' => 'sessions#destroy' 
 
 

end

app/views/layouts/_signin.html.erb
 

  
	<%= form_for(:session, :url => sessions_path,:html => {:class => "navbar-form navbar-right signin"}) do |f| %>
  		<div class="form-group">
   		 <%= f.text_field :email , :placeholder=>"Email", :class=>"form-control" %>
 		 </div>
  		<div class="form-group">
   		 <%= f.password_field :password, :placeholder=>"Password", :class=>"form-control" %>
  		</div>
 	 <%= f.submit "Sign in", :class=>"btn btn-success" %>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<div class="navbar navbar-inverse navbar-ﬁxed-top" role="navigation">     
	<div class="container">    
		<div class="navbar-header">         
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar- collapse">          
				 <span class="sr-only">Toggle navigation</span>          
				 <span class="icon-bar"></span>           
				 <span class="icon-bar"></span>           
				 <span class="icon-bar"></span>         
		    </button>
		    
		    <a><%= link_to "Demo Blog" , root_path, :class=>'navbar-brand' %></a>
		          </div>
			<div class="navbar-collapse collapse">         
				<ul class="nav navbar-nav">   
				 <li><%= link_to "About" , about_path %></li>           
				
				<% if signed_in? %>
					<li><%= link_to "Users" , users_path %></li>  
					<li id="fat-menu" class="dropdown">
						<a href="a" class="dropdown-toggle"data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile" , user_path(current_user)%></li>           
							<li><%= link_to "Settings" , edit_user_path(current_user) %></li>           
					             
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out",signout_path , method: "delete" %>
							</li>
						</ul>
					</ul> 
				<% else %>
					<li><%= link_to "Sign Up" , signup_path %></li>
					</ul>
					<%= render 'layouts/signin'%>   
				<% end %>
			</div><!--/.navbar-collapse -->     
		</div>   
	</div>

</div>


<body>
		<% flash.each do |name, msg| %>
 			<% if msg.is_a?(String) %>
 			<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
 				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
 				<%= content_tag :div, msg, :id => "ﬂash_#{name}" %>
 			</div>
 			<% end %>
		<% end %>

<%= yield %>
<%= debug(params) if Rails.env.development?%>
</body> 
</html>